2019-08-30 21:13:03,983 INFO Number:0
2019-08-30 21:13:03,983 INFO Number:1
2019-08-30 21:13:03,983 INFO Number:2
2019-08-30 21:13:03,983 INFO Number:3
2019-08-30 21:13:03,984 INFO Number:4
2019-08-30 21:13:03,984 INFO Number:5
2019-08-30 21:13:03,984 INFO Number:6
2019-08-30 21:13:03,984 INFO Number:7
2019-08-30 21:13:03,984 INFO Number:8
2019-08-30 21:13:03,984 INFO Number:9
2019-08-30 21:13:04,021 ERROR This is error
Traceback (most recent call last):
  File "for_gen_num.py", line 9, in <module>
    1/0
ZeroDivisionError: integer division or modulo by zero
